name: convenient_test_common_dart
description: Write and debug tests easily, built on integration_test
version: 1.0.1+3
repository: https://github.com/fzyzcjy/flutter_convenient_test
environment:
  sdk: '>=2.15.1 <3.0.0'
dependencies:
  collection: ^1.15.0
  fixnum: ^1.0.0
  grpc: ^3.0.0
  mobx: ^2.0.7
  protobuf: ^2.0.0
  quiver: ^3.0.1+1
  tuple: ^2.0.0
dev_dependencies:
  lint: ^1.8.2
