targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          # https://github.com/google/json_serializable.dart/issues/557#issuecomment-618260593
          ignore_for_file:
            - implicit_dynamic_parameter
            - non_constant_identifier_names
            - duplicate_ignore
