name: convenient_test_dev
description: TODO_description
version: 1.0.0
repository: https://github.com/fzyzcjy/flutter_convenient_test

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  collection: ^1.15.0
  convenient_test: ^1.0.0
  convenient_test_common: ^1.0.0
  fixnum: ^1.0.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  get_it: ^6.0.0
  grpc: ^3.0.0
  integration_test:
    sdk: flutter
  intl: ^0.17.0
  lint: ^1.8.2
  meta: ^1.3.0
  path_provider: ^2.0.9
  pedantic: ^1.11.0
  recase: ^4.0.0-nullsafety.0
  test_api: ^0.4.2
  web_socket_channel: ^2.1.0

dependency_overrides:
  convenient_test:
    path: ../convenient_test
  convenient_test_common:
    path: ../convenient_test_common
