name: convenient_test
description: A new flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter

dev_dependencies:
  lint: ^1.8.2
