name: convenient_test
description: TODO_description
version: 1.0.0
repository: https://github.com/fzyzcjy/flutter_convenient_test

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2
