name: convenient_test_common
description: Write and debug tests easily, built on integration_test
version: 1.1.0
repository: https://github.com/fzyzcjy/flutter_convenient_test
environment:
  sdk: '>=2.15.1 <3.0.0'
dependencies:
  collection: ^1.15.0
  convenient_test_common_dart: ^1.0.0
  fixnum: ^1.0.0
  flutter:
    sdk: flutter
  grpc: ^3.0.0
  mobx: ^2.0.7
  protobuf: ^2.0.0
  quiver: ^3.0.1+1
  tuple: ^2.0.0
dev_dependencies:
  dart_code_metrics: ^4.15.0
  flutter_test:
    sdk: flutter
  lint: ^1.8.2

dependency_overrides:
  convenient_test_common_dart:
    path: ../convenient_test_common_dart
