name: efficient_test_common
description: A new flutter plugin project.
version: 0.0.1
environment:
  sdk: '>=2.15.1 <3.0.0'
dependencies:
  collection: ^1.15.0-nullsafety.4
  flutter:
    sdk: flutter
  mobx: ^2.0.7
  protobuf: ^2.0.0
  quiver: ^3.0.1+1
  tuple: ^2.0.0
dev_dependencies:
  lint: ^1.8.2
