name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 10 * * *'

jobs:
  flutter:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        channel:
          # - beta # too different from stable, thus analyzer will complain
          - stable
        package_name:
          - convenient_test
          - convenient_test_common
          - convenient_test_dev
          - convenient_test_manager

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.channel }}

      - name: Install dependencies
        run: flutter pub get
        working-directory: packages/${{ matrix.package_name }}

      - name: Check format
        run: flutter format --set-exit-if-changed --line-length 120 .
        working-directory: packages/${{ matrix.package_name }}

      - name: Analyze
        run: flutter analyze
        working-directory: packages/${{ matrix.package_name }}

      - name: Run tests
        run: flutter test
        working-directory: packages/${{ matrix.package_name }}
