name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 10 * * *'

jobs:
  flutter:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        channel:
          # - beta # too different from stable, thus analyzer will complain
          - stable
        package_name:
          - convenient_test
          - convenient_test/example
          - convenient_test_common
          - convenient_test_common_dart
          - convenient_test_dev
          - convenient_test_manager
          - convenient_test_manager_dart

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.channel }}

      - name: Install dependencies
        run: flutter pub get
        working-directory: packages/${{ matrix.package_name }}

      - name: Analyze
        run: flutter analyze
        working-directory: packages/${{ matrix.package_name }}

      - name: Dart code metrics
        run: flutter pub run dart_code_metrics:metrics analyze lib --fatal-style --fatal-performance --fatal-warnings --set-exit-on-violation-level noted
        working-directory: packages/${{ matrix.package_name }}

      - name: Run tests
        run: flutter test
        working-directory: packages/${{ matrix.package_name }}

      - name: Check format
        run: flutter format --set-exit-if-changed --line-length 120 .
        working-directory: packages/${{ matrix.package_name }}


  build_manager_macos:
    runs-on: macOS-11

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      
      - name: Enable Macos
        run: flutter config --enable-macos-desktop

      - name: Install dependencies
        run: flutter pub get
        working-directory: packages/convenient_test_manager

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'

      - name: setup-cocoapods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          version: latest

      - name: flutter build
        run: flutter build macos
        working-directory: packages/convenient_test_manager/macos

      - name: build_mac_app
        run: bundle exec fastlane run build_mac_app export_method:mac-application scheme:Runner output_directory:./build
        working-directory: packages/convenient_test_manager/macos

      - name: Tar outputs
        run: cd packages/convenient_test_manager/macos/build && tar cvf convenient_test_manager.app.tar convenient_test_manager.app

      - uses: actions/upload-artifact@v3
        with:
          name: manager_macos
          path: packages/convenient_test_manager/macos/build/convenient_test_manager.app.tar
